# 异常

异常处理是指预估代码在执行过程中可能出现的错误，最大程度避免由于错误的发生导致整个程序无法继续运行。

## throw 抛异常

throw 指当有错误时，抛出错误信息。但是在抛出错误之后，程序就会终止运行。当 Error 对象配合 throw 使用时，能够设置更详细的错误信息。

```js
// throw 抛异常
function fn(x, y) {
  if (!x || !y) {
    throw new Error("未传入参数");
    /*
    index.html:13 Uncaught Error: 未传入参数
    at fn (index.html:13:17)
    at index.html:17:19
    */
  }
  return x + y;
}
console.log(fn());
```

## try/catch 捕获异常

```js
function fn() {
  try {
    // 可能出现错误的代码
    const p = querySelector("P");
    p.style.color = "red";
  } catch (err) {
    // err 错误信息
    console.log(err.message);
    throw new Error("错误");
    // 不执行下列代码
    return;
  } finally {
    // 无论程序是否错误都会执行的代码
    alert("结束！");
  }
  console.log("test");
}
fn();
```

## debugger 调试

代码中使用 debugger 设置断点。
